version: '3.8'
services:
  db-vendas:
    image: postgres:latest
    networks:
      - network-vendas
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: Loja
      POSTGRES_USER: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
  cmp-vendas:
    build: .
    image: entityblackhawk/cmp-vendas:latest
    environment:
      DATABASE_HOST_PORT: db-vendas:5432
    networks:
      - network-vendas
    ports:
      - "8080:8080"
    depends_on:
        - db-vendas
networks:
  network-vendas:
    driver: bridge