version: '3.8'
services:
  db_vendas:
    image: postgres:latest
    networks:
      - network_vendas
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: Loja
      POSTGRES_USER: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
  cmp_vendas:
    build: .
    image: entityblackhawk/cmp-vendas:latest
    networks:
      - network_vendas
    ports:
      - "8080:8080"
    depends_on:
        - db_vendas
networks:
  network_vendas:
    driver: bridge